openapi: 3.0.3
info:
  title: Density Ruler Vlab RESTful API
  version: 1.0.0
  description: |-
    Berikut adalah API yang digunakan dalam mendukung proses berjalannya virtual lab [Density Ruler](https://naditjandra.github.io/densityruler/).
    
    Some useful links:
    - [Density Ruler repository](https://github.com/naditjandra/densityruler)

servers:
  - url: https://naditjandra.github.io/densityruler/Density%20Ruler
    description: Main server

tags:
  - name: User
    description: Operations related to user.

paths:
  /user.json:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML
      tags:
        - User
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string